# define deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipe-api
  labels: 
    app: recipe-api
# describe how replica set works
spec:
  replicas: 5
  selector:
    matchLabels:
      app: recipe-api
  template:
    metadata:
      labels:
        app: recipe-api
# define pod's container
    spec:
      containers:
      - name: recipe-api
        image: recipe-api:v1
        ports:
        - containerPort: 1337
        livenessProbe:
          httpGet:
            path: /recipes/42
            port: 1337
          initialDelaySeconds: 3
          periodSeconds: 10
